version: '3.8'


services:
  php:
    image: php:7.4-cli
    working_dir: /usr/src/hpt-test-grabber
    volumes:
      - ./src:/usr/src/hpt-test-grabber/src:ro
      - ./run.php:/usr/src/hpt-test-grabber/run.php:ro
